UserTable:
  Type: 'AWS::DynamoDB::Table'
  DeletionPolicy: Retain
  Properties:
    AttributeDefinitions:
      -
        AttributeName: id
        AttributeType: S
      -  
        AttributeName: userId
        AttributeType: S  
    KeySchema:
      -
        AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - 
        IndexName: userId-index
        KeySchema:
          - 
            AttributeName: "userId"
            KeyType: "HASH"
        Projection:
          ProjectionType: "ALL"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5   
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5      
    TableName: ${self:custom.UserTable}   
